name: bonjour

run-name: bonjour

on:
  push:
    branches: [main]

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Afficher Bonjour
        run: echo "Bonjour depuis GitHub Actions !"

      - name: Lister les fichiers
        run: ls -la

  afficher-version:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Afficher la version de Java
        run: java --version

      - name: Afficher la version de Maven
        run: mvn --version

      - name: Afficher les fichiers
        run: ls -la